version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 10
    labels:
      - 'type: dependencies'
      - 'type: automerge'
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: react
        versions:
          - '>=18.0.0'
      - dependency-name: react-dom
        versions:
          - '>=18.0.0'
      - dependency-name: react-test-renderer
        versions:
          - '>=18.0.0'
      - dependency-name: '@types/react'
        versions:
          - '>=18.0.0'
      - dependency-name: '@types/react-dom'
        versions:
          - '>=18.0.0'
      - dependency-name: '@storybook/react'
        versions:
          - '^6.0.21'
      - dependency-name: '@storybook/addon-essentials'
        versions:
          - '^6.1.5'
      - dependency-name: 'uswds'

  - package-ecosystem: npm
    directory: '/example/'
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 10
    labels:
      - 'type: dependencies'
      - 'type: automerge'
      - 'type: example'
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: react
        versions:
          - '>=18.0.0'
      - dependency-name: react-dom
        versions:
          - '>=18.0.0'
      - dependency-name: '@types/react'
        versions:
          - '>=18.0.0'
      - dependency-name: '@types/react-dom'
        versions:
          - '>=18.0.0'
