version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 10
    labels:
      - 'type: dependencies'
      - 'type: automerge'
    allow:
      - dependency-type: development
    ignore:
      - dependency-name: react
        versions:
          - '^16.11.0'
      - dependency-name: react-dom
        versions:
          - '^16.11.0'
      - dependency-name: '@types/react'
        versions:
          - '^16.10.0'
      - dependency-name: '@types/react-dom'
        versions:
          - '^16.10.0'
      - dependency-name: '@storybook/react'
        versions:
          - '^6.0.21'
      - dependency-name: '@storybook/addon-docs'
        versions:
          - '^6.0.21'
      - dependency-name: '@storybook/addon-viewport'
        versions:
          - '^6.0.21'

  - package-ecosystem: npm
    directory: '/example/'
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 10
    labels:
      - 'type: dependencies'
      - 'type: automerge'
      - 'type: example'
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: react
        versions:
          - '^16.13.1'
      - dependency-name: react-dom
        versions:
          - '^16.13.1'
      - dependency-name: '@types/react'
        versions:
          - '^16.9.0'
      - dependency-name: '@types/react-dom'
        versions:
          - '^16.9.0'
